-- Test-only schema (SQLite). Production uses ../schema.sql on MySQL.
CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL,
  dj_name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, tagline TEXT NOT NULL DEFAULT '', genres TEXT NOT NULL DEFAULT '',
  min_tip REAL NOT NULL DEFAULT 0, pay_json TEXT NOT NULL, design_json TEXT NOT NULL,
  logo_media INTEGER NULL, wall_media INTEGER NULL, photos_json TEXT NOT NULL, is_live INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL
);
CREATE TABLE sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE, expires_at INTEGER NOT NULL
);
CREATE TABLE media (
  id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  mime TEXT NOT NULL, data BLOB NOT NULL, created_at INTEGER NOT NULL
);
CREATE TABLE requests (
  id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, event_id INTEGER NULL,
  guest_name TEXT NOT NULL DEFAULT '', song_title TEXT NOT NULL, artist TEXT NOT NULL DEFAULT '', message TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new','approved','declined','played')),
  amount REAL NOT NULL DEFAULT 0, method TEXT NOT NULL DEFAULT '', paid INTEGER NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL, played_at INTEGER NULL
);
