import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {URL} from 'node:url';
const PORT=Number(process.env.PORT||8765),CONFIG_PATH=process.env.DJRL_BRIDGE_CONFIG||path.join(process.cwd(),'config.json');
function cfg(){try{return JSON.parse(fs.readFileSync(CONFIG_PATH,'utf8'))}catch{return{source:'virtualdj',virtualdj:{baseUrl:'http://127.0.0.1:80',bearer:''}}}}
let state={connected:false,source:null,nowPlaying:null,updatedAt:null,error:null};
function out(res,status,body){res.writeHead(status,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Private-Network':'true','Cache-Control':'no-store'});res.end(JSON.stringify(body))}
async function q(base,bearer,script){const u=new URL('/query',base);u.searchParams.set('script',script);const r=await fetch(u,{headers:bearer?{Authorization:'Bearer '+bearer}:{}});if(!r.ok)throw Error('VirtualDJ HTTP '+r.status);return(await r.text()).trim()}
async function vdj(){const c=cfg().virtualdj||{},base=c.baseUrl||'http://127.0.0.1:80';try{const a=await q(base,c.bearer||'','deck master is_audible');if(['false','0',''].includes(a)){state={connected:true,source:'virtualdj',nowPlaying:null,updatedAt:Date.now(),error:null};return}const [artist,title,bpm,key,genre,elapsed]=await Promise.all(['artist','title','bpm','key','genre'].map(x=>q(base,c.bearer||'','deck master get_'+x)).concat([q(base,c.bearer||'','deck master get_time elapsed')]));state={connected:true,source:'virtualdj',nowPlaying:{artist,title,bpm:Number(bpm)||null,key:key||null,genre:genre||null,elapsedMs:Number(elapsed)||null},updatedAt:Date.now(),error:null}}catch(e){state={...state,connected:false,error:e.message}}}
function rb(){const f=cfg().rekordbox?.historyFile;if(!f)return null;try{const l=fs.readFileSync(f,'utf8').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).pop();if(!l)return null;const p=l.split(/\t|,/).map(x=>x.trim());return p.length>=2?{artist:p[0],title:p[1],source:'rekordbox-history'}:null}catch{return null}}
async function poll(){const c=cfg();if(c.source==='rekordbox-history'){const n=rb();state={connected:!!n,source:'rekordbox-history',nowPlaying:n,updatedAt:Date.now(),error:n?null:'Waiting for Rekordbox history file'}}else await vdj()}setInterval(poll,2000);poll();
http.createServer((req,res)=>{const u=new URL(req.url,'http://127.0.0.1:'+PORT);if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,OPTIONS','Access-Control-Allow-Private-Network':'true'});return res.end()}if(u.pathname==='/health'||u.pathname==='/now-playing')return out(res,200,state);if(u.pathname==='/config')return out(res,200,{source:cfg().source||'virtualdj',port:PORT,host:os.hostname()});out(res,404,{error:'not_found'})}).listen(PORT,'127.0.0.1',()=>console.log('DJ Request Live Bridge: http://127.0.0.1:'+PORT));